# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa831449b8c3e842bbc326e6d25325945d3b2474227c3569cc0db4e4098da494e32543197f589ad39f72951eecde3a961c20dd0a87717ae8ed4d17a8bb82149

test:
  secret_key_base: 4850d65fe4abbfebc502b8be941d1ef8bd4e7cdfe2947893909506f29a6a16f9333f2877473db94eedd2bbb974fe4c0f89dcd976dd723ea6076efbe12af48cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
